---
- name: sync packages across all servers
  hosts: shell-servers
  sudo: yes

  tasks:
  - pip: name='git+https://github.com/hashbang/provisor/#egg=provisor'
  - pip: name='git+https://github.com/hashbang/hashbangctl/#egg=hashbangctl'
